name: Thunderscan
on:
  push:
    branches: [ master ]
jobs:
  Thunderscan:
    name: Thunerscan 
    runs-on: ubuntu-latest
    env:
      SASTCLI_TOKEN: ${{ secrets.SASTCLI_TOKEN }}
      SAST_SERVER:   ${{ secrets.SAST_SERVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Thunderscan Binary 
        run: |
          wget https://downloads-sast.mend.io/sast-cli/linux/mendsastcli
          chmod +x mendsastcli
      - name: Debug
        run: |
          ls -latr
          find .
      - name: Run Thunderscan
        run: |
          ./mendsastcli --app "k8s Sample App" --report formats "html,json" --filename "report" --name "K8s Sample App" --dir ./backend
