name: GGShield Python
on:
  push:
    branches: [ main ]
jobs:
  GGShield:
    name: GGSheild 
    runs-on: self-hosted
    env:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker
        run: |
          sleep 2m
          docker run -t --rm --platform linux/amd64 -v `pwd`:/scan -e GITGUARDIAN_API_KEY=$GITGUARDIAN_API_KEY gitguardian/ggshield:v1.12.0 ggshield secret scan path /scan --recursive -y 
